apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: stock
spec:
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: stock
        port:
          number: 3000
