apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory
spec:
  hosts:
  - "*"
  gateways:
  - inventory-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: gateway
        port:
          number: 3000
