apiVersion: k3d.io/v1alpha5
kind: Simple
network: istio-demo-poc-k3d
ports:
  - port: 8082:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      # - arg: --tls-san=https://istio.simonlucido.com
      #   nodeFilters:
      #     - servers:*
      - arg: --disable=traefik
        nodeFilters:
          - servers:*
